### ISSUE TITLE
 Class 'Keevitaja\Linguist\UriFixer' not found

### ISSUE THREAD

**Issue by johnef** [keevitaja/linguist#13]
I installed the package 
`composer require keevitaja/linguist`
and going with option 1
Add following line after the vendor autoloading to your projects public/index.php file.
(new Keevitaja\Linguist\UriFixer)->fixit();
Got
 `Class 'Keevitaja\Linguist\UriFixer' not found`

**Comment by keevitaja** [comment]
Sorry, i cannot reproduce this on L5.5.  

If you're using older version of laravel you need to add the service provider to your `config/app.php`

Check that your opcache is cleared.

**Comment by johnef** [comment]
I am sorry didn't clear my Laravel version I am using Laravel 5.4, and how to clean my opcache, by the way there is one thing I try `composer dump-autoload` but no luck

**Comment by keevitaja** [comment]
in 5.4 you also need to add `Keevitaja\Linguist\LinguistServiceProvider` to your `app/config.php` service providers array.

but again this error says laravel cannot find the package. check your vendor folder and try if other packages are discoverable.
