### ISSUE TITLE
Question: Would a subdomain work as well?

### ISSUE THREAD

**Issue by pmochine** [keevitaja/linguist#15]
I'm curious if it is somehow possible, it would so cool to have it like de.myapp.com or fr.myapp.com or for default english just myapp.com

**Comment by keevitaja** [comment]
at the moment it does not support this feature, but this is pretty easy to implement.

you could just set the requested locale with `define('INTERCEPTED_LOCALE', 'fr')` based on your domain.

i have actually a newer version of linguist on my queue list with better laravel support. i might implement this.
