### ISSUE TITLE
Getting config variables

### ISSUE THREAD

**Issue by cdarken** [keevitaja/linguist#2]
Took a look at your package and it looks interesting. But looking through sources I've found this code:

```
$config = include __DIR__.'/../../config/linguist.php';
$pattern = '/^\/('.implode('|', $config['locales']).')(?:\/|$)/';
```

in https://github.com/keevitaja/linguist/blob/master/src/Http/Kernel.php#L30

Shouldn't actually be:

```
$pattern = '/^\/('.implode('|', Config::get('linguist.locales').')(?:\/|$)/';
```

as you've already merged the configs in the service provider?

Just trying to prevent a future problem here, maybe I'm wrong.

**Comment by keevitaja** [comment]
At this point the ServiceProviders are not loaded. The whole idea is to remove the locale from the URI before anything else.

https://github.com/laravel/laravel/blob/master/bootstrap/app.php#L29

**Comment by cdarken** [comment]
Ok, I get it now. That's how you manage the removal of the locale from the url.
Also, this repo is getting closer to 50 stars. Here's to 1000! :)
